apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-pv-prod
  labels:
    type: nfs
    environment: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/colli369
    server: 10.48.10.216
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      type: nfs
      environment: prod
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prod-deployment
  labels:
    app: flask-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-prod
  template:
    metadata:
      labels:
        app: flask-prod
    spec:
      containers:
        - name: flask
          image: cithit/colli369:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: nfs-storage
              mountPath: /nfs       
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: flask-pvc-prod    
---
apiVersion: v1
kind: Service
metadata:
  name: flask-prod-service
spec:
  type: LoadBalancer 
  loadBalancerIP: 10.48.10.170
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: flask-prod
