apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Add this line
  nfs:
    path: /srv/nfs/colli369
    server: 10.48.10.138
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Add this line
  selector:
    matchLabels:
      type: nfs
