+ kubectl apply -f deployment-dev.yaml
persistentvolumeclaim/flask-pvc unchanged
deployment.apps/flask-deployment created
service/flask-dev-service configured
The PersistentVolume "flask-pv" is invalid: spec.persistentvolumesource: Forbidden: spec.persistentvolumesource is immutable after creation
  core.PersistentVolumeSource{
  	... // 2 identical fields
  	HostPath:  nil,
  	Glusterfs: nil,
  	NFS: &core.NFSVolumeSource{
- 		Server:   "10.48.10.140",
+ 		Server:   "10.48.10.138",
  		Path:     "/srv/nfs/colli369",
  		ReadOnly: false,
  	},
  	RBD:     nil,
  	Quobyte: nil,
  	... // 15 identical fields
  }
